### ISSUE TITLE
The certificate is expired for API doc site

### ISSUE THREAD

**Issue by peter279k** [sunrise-php/vin#23]
As title, the API doc site certificate is expired.

It looks like the certificate uses the `Let's Encrypt X3` and it has been expired for about 10 days ago.

It should renew the certificate now and I suggest that this renew work should add in the `cron job` setting in Linux operating system.

**Comment by fenric** [comment]
@peter279k Thank you. Yes, I see, there really is a problem.

Periodically, certificates expire in subdomains, although the update is performed once a week automatically...

I will correct as soon as possible. By the way, the documentation is not finished there yet, I plan to update this site.

**Comment by peter279k** [comment]
@fenric, I think we should track this issue and keep it open until the official doc is available :).

**Comment by fenric** [comment]
no anchor, no problem :)
