### ISSUE TITLE
Failed to create an object with valid VIN

### ISSUE THREAD

**Issue by mindcrimer** [sunrise-php/vin#59]
Hello!
Thank you for you good class!
I found that's not possible to instantiate an object with this 100% valid VIN 'Х89557131DWAH5428'.

**Comment by fenric** [comment]
Hi @mindcrimer!

The valid VIN it's a string of 17 chars in length:

https://en.wikipedia.org/wiki/Vehicle_identification_number

You can also study ISO 3779 and 3780...

I have no info that the VIN can be longer than 17 chars... and you?
