### ISSUE TITLE
missing WMI

### ISSUE THREAD

**Issue by le-bru** [sunrise-php/vin#70]
hi there,
i think that you are missing some WMI in the manufacturers.php
`    'W1K' => 'Mercedes',
    'W1V' => 'Mercedes',
    'W1N' => 'Mercedes',
    'YAR' => 'Toyota',
    'WAP' => 'BMW'`

could you mabe add them?

thanks!

**Comment by fenric** [comment]
`W1K `, `W1V` and `W1N` – `Mercedes`, it's correct.

`WAP` – `Alpine` (BMW tuning), but I agree, it's `BMW`.

`YAR` – I can't found, do u have a source to confirm this?

**Comment by le-bru** [comment]
Hi, thanks for getting back to me.
Source Toyota:
http://www.toyota-tech.eu/toms_cabs/EN/4KET-1370.pdf

**Comment by fenric** [comment]
done [v1.1.4](https://github.com/sunrise-php/vin/releases/tag/v1.1.4)
