### ISSUE TITLE
Missing WMI Tesla China Built

### ISSUE THREAD

**Issue by maxresnikoff** [sunrise-php/vin#76]
A few Tesla WMIs are missing
<img width="457" alt="image" src="https://user-images.githubusercontent.com/48560713/189962210-9df3274b-0816-427b-96a9-deba390a1fc1.png">

Source: https://tesla-info.com/vin-decoder.php

**Comment by fenric** [comment]
https://github.com/sunrise-php/vin/releases/tag/v1.3.0
